# Generated by Django 5.1.7 on 2025-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_show_reservation_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="reservation_price",
        ),
        migrations.AddField(
            model_name="show",
            name="buy_ticket_online",
            field=models.BooleanField(
                default=False,
                help_text="Set to true, if tickets are bought, not reserved, online.",
            ),
        ),
        migrations.AddField(
            model_name="show",
            name="ticket_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="schluss"),
        ),
    ]
