# Generated by Django 5.1.7 on 2025-08-20 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_sitestats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end",
        ),
    ]
