# Generated by Django 5.2.8 on 2025-11-28 21:00

import tinymce.models
from django.db import migrations


def convert_markdown_to_html(apps, schema_editor):
    """Convert existing Markdown content to HTML"""
    try:
        import markdown
    except ImportError:
        print("Warning: Neither 'markdown' nor 'markdown2' package found. Skipping conversion.")
        return

    Show = apps.get_model("events", "Show")

    for show in Show.objects.all():
        # Convert description if it contains markdown
        if show.description:
            show.description = markdown.markdown(show.description)

        # Convert cast if it contains markdown
        if show.cast:
            show.cast = markdown.markdown(show.cast)

        show.save()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_remove_event_end"),
    ]

    operations = [
        # First, convert existing markdown data to HTML
        migrations.RunPython(convert_markdown_to_html, reverse_code=migrations.RunPython.noop),
        # Then change the field types
        migrations.AlterField(
            model_name="show",
            name="cast",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="show",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
