# Generated by Django 5.2.10 on 2026-01-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_show_cast_alter_show_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpcomingShow",
            fields=[],
            options={
                "verbose_name": "Upcoming show",
                "verbose_name_plural": "Upcoming shows",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("events.show",),
        ),
        migrations.AddField(
            model_name="reservation",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
