# Generated by Django 5.2.9 on 2025-12-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_reservationpayment_custom_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='max_ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price for sliding scale. Defaults to ticket_price + 10 EUR if not set.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='min_ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price for sliding scale. Defaults to ticket_price - 10 EUR if not set.', max_digits=8, null=True),
        ),
    ]
