# Generated by Django 5.2.9 on 2025-12-14 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_show_max_ticket_price_show_min_ticket_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="buy_ticket_online",
        ),
    ]
