# Generated by Django 5.2.9 on 2025-12-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_show_buy_ticket_online'),
    ]
