# Generated by Django 5.2.12 on 2026-03-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_merge_20260117_1143"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="third_party_reservation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="show",
            name="third_party_reservation_link",
            field=models.CharField(default=False),
        ),
    ]
