# Generated by Django 5.2.13 on 2026-04-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_show_third_party_reservation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='ticket_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]