# Generated by Django 5.2.13 on 2026-05-19 19:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_migrate_and_delete_newsletteremail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['admission']},
        ),
        migrations.AlterField(
            model_name='guest',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
