# Generated by Django 5.2.14 on 2026-05-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_reservation_capacity_alter_event_show_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show',
        ),
        migrations.DeleteModel(
            name='SiteStats',
        ),
        migrations.DeleteModel(
            name='UpcomingShow',
        ),
    ]
