# Generated by Django 5.2.14 on 2026-05-22 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_delete_show_delete_sitestats_delete_upcomingshow"),
        ("reservations", "0004_migrate_payment_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="reservant",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="event",
        ),
        migrations.RemoveField(
            model_name="reservationpayment",
            name="reservation",
        ),
        migrations.DeleteModel(
            name="Guest",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
        migrations.DeleteModel(
            name="ReservationPayment",
        ),
    ]
