# Generated by Django 5.2.14 on 2026-05-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_reservation_reservant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastEvent',
            fields=[
            ],
            options={
                'verbose_name': 'past event',
                'verbose_name_plural': 'past events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
            ],
            options={
                'verbose_name': 'upcoming event',
                'verbose_name_plural': '  Upcoming events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('events.event',),
        ),
    ]
