# Generated by Django 5.2.14 on 2026-06-08 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_pastevent_upcomingevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['admission'], 'verbose_name_plural': 'all events'},
        ),
    ]
