//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config";

export default [
  ...tanstackConfig,
  {
    rules: {
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
      "func-style": ["error", "expression", { allowArrowFunctions: true }],
      "prefer-arrow-callback": "error",
    },
  },
  {
    ignores: [
      "eslint.config.js",
      "src/routeTree.gen.ts",
      // vendored shadcn/ui components, regenerated by the shadcn CLI
      "src/components/ui/**",
      // build / generated output
      ".output/**",
      ".nitro/**",
      ".tanstack/**",
      ".wrangler/**",
      ".vinxi/**",
    ],
  },
];
