# Generated by Django 5.2.14 on 2026-05-22 09:29


import image_cropping.fields
import tinymce.models
from django.db import migrations, models



def copy_shows_forward(apps, schema_editor):
    Show = apps.get_model("shows", "Show")
    OldShow = apps.get_model("events", "Show")

    for old in OldShow.objects.all():
        Show.objects.create(
            id=old.id,
            title=old.title,
            description=old.description,
            cast=old.cast,
            video_link=old.video_link,
            card_image=old.card_image,
            website_link=old.website_link,
            banner_link=old.banner_link,
            private=old.private,
            third_party_reservation=old.third_party_reservation,
            third_party_reservation_link=old.third_party_reservation_link,
            reservation_price=old.reservation_price,
            base_ticket_price=old.ticket_price,
            min_ticket_price=old.min_ticket_price,
            max_ticket_price=old.max_ticket_price,
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('events', '0015_alter_event_options_alter_guest_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", tinymce.models.HTMLField()),
                ("cast", tinymce.models.HTMLField()),
                ("video_link", models.CharField(blank=True, max_length=255)),
                ("card_image", models.ImageField(upload_to="")),
                ("website_link", models.CharField(blank=True, max_length=255)),
                ("banner_link", models.ImageField(blank=True, upload_to="")),
                (
                    "head_img",
                    image_cropping.fields.ImageRatioField(
                        "banner_link",
                        "400x225",
                        adapt_rotation=False,
                        allow_fullsize=False,
                        free_crop=False,
                        help_text=None,
                        hide_image_field=False,
                        size_warning=False,
                        verbose_name="head img",
                    ),
                ),
                ("private", models.BooleanField(default=False)),
                ("third_party_reservation", models.BooleanField(default=False)),
                ("third_party_reservation_link", models.CharField(blank=True, max_length=255)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("reservation_price", models.PositiveIntegerField(blank=True, null=True)),
                ("base_ticket_price", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_ticket_price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum price for sliding scale. Defaults to base_ticket_price - 10 EUR if not set.",
                        null=True,
                    ),
                ),
                (
                    "max_ticket_price",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum price for sliding scale. Defaults to base_ticket_price + 10 EUR if not set.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PastShow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shows.show",),
        ),
        migrations.CreateModel(
            name="UnscheduledShow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shows.show",),
        ),
        migrations.CreateModel(
            name="UpcomingShow",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shows.show",),
        ),
        migrations.RunPython(
            code=copy_shows_forward,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
