# Generated by Django 5.2.14 on 2026-05-22 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0002_remove_show_head_img_show_seo_image_crop_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pastshow",
            options={"verbose_name": "past show", "verbose_name_plural": "past shows"},
        ),
        migrations.AlterModelOptions(
            name="show",
            options={"verbose_name_plural": "all shows"},
        ),
        migrations.AlterModelOptions(
            name="unscheduledshow",
            options={
                "verbose_name": "unscheduled show",
                "verbose_name_plural": " Unscheduled shows",
            },
        ),
        migrations.AlterModelOptions(
            name="upcomingshow",
            options={"verbose_name": "upcoming show", "verbose_name_plural": "  Upcoming shows"},
        ),
    ]
