# Generated by Django 5.2.14 on 2026-05-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0004_rename_banner_link_show_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="seo_image_crop",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="seo image crop"
            ),
        ),
    ]
