# Generated by Django 5.2.15 on 2026-09-05 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0006_reset_show_sequence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="seo_image_crop",
        ),
    ]
