# Generated by Django 5.2.14 on 2026-05-22 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models

def copy_reservations(apps, schema_editor):
    OldReservation = apps.get_model('events', 'Reservation')
    OldGuest = apps.get_model('events', 'Guest')
    NewReservation = apps.get_model('reservations', 'Reservation')
    NewGuest = apps.get_model('reservations', 'Guest')

    for old in OldReservation.objects.select_related('reservant').all():
        p = old.reservant
        new = NewReservation.objects.create(
            id=old.id,
            event=old.event,
            first_name=p.firstname,
            last_name=p.surname,
            email=p.email or '',
            checked_in=old.checked_in,
        )
        for old_guest in OldGuest.objects.select_related('person_ptr').filter(event_reservation=old):
            NewGuest.objects.create(
                reservation=new,
                first_name=old_guest.firstname,
                last_name=old_guest.surname,
                ticket_id=old_guest.ticket_id or uuid.uuid4(),
                checked_in=old_guest.checked_in,
            )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0017_delete_show_delete_sitestats_delete_upcomingshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('checked_in', models.BooleanField(default=False)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checked_in', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reservations.reservation')),
            ],
        ),
        migrations.RunPython(copy_reservations, reverse_code=migrations.RunPython.noop),
    ]
