# Generated by Django 5.2.14 on 2026-05-22 18:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0002_reservationpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="ticket_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
