# Generated by Django 5.2.15 on 2026-07-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0009_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Card"),
                    ("paypal", "Paypal"),
                    ("apple", "Apple"),
                    ("google", "Google"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
