# Generated by Django 5.2.15 on 2026-09-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0011_backfill_payment_from_legacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("card", "Card"),
                    ("paypal", "Paypal"),
                    ("apple", "Apple"),
                    ("google", "Google"),
                    ("klarna", "Klarna"),
                    ("link", "Link"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
