# Generated by Django 5.2.15 on 2026-09-06 14:38

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PopUpElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title_de", models.CharField(max_length=100)),
                ("title_en", models.CharField(max_length=100)),
                ("message_de", tinymce.models.HTMLField(max_length=1000)),
                ("message_en", tinymce.models.HTMLField(max_length=1000)),
                ("active", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
