# Generated by Django 5.2.15 on 2026-09-06 13:33

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PopUpElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", tinymce.models.HTMLField(max_length=1000)),
                ("active", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=255)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("top_right", "Top Right"),
                            ("bottom_right", "Bottom Right"),
                        ],
                        default="bottom_right",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
