# Generated by Django 5.2.14 on 2026-05-20 08:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentalobject",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
    ]
