services:
  postgres:
    image: postgres:16.1
    container_name: staging_postgres
    restart: always
    volumes:
      - zm_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=monddb
      - POSTGRES_USER=mond
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  django:
    hostname: staging_zirkusmond_de
    image: ${DOCKER_USERNAME}/zirkusmond:staging
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - zm_media:/srv/data
    depends_on:
      - postgres

networks:
  default:
    external: true
    name: ubuntu_default

volumes:
  zm_media:
  zm_db:
