services:
  postgres:
    image: postgres:16.1
    restart: always
    volumes:
      - zm_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=monddb
      - POSTGRES_USER=mond
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  django:
    hostname: django
    image: ${DOCKER_USERNAME}/zirkusmond:staging
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - zm_media:/srv/data
    depends_on:
      - postgres

  nginx:
    image: nginx
    depends_on:
      - django
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/nginx/sites.d/staging_zirkusmond.conf:/etc/nginx/sites.d/staging_zirkusmond.conf:ro
      - /home/ubuntu/nginx/certs:/certs/:ro
      - /home/ubuntu/nginx/acme:/var/www/acme-challenge
      - zm_media:/var/www/html_zm
      - /var/log/nginx-docker:/var/log/nginx
    restart: always

networks:
  default:
    driver: bridge

volumes:
  zm_media:
  zm_db: