# Generated by Django 5.2.8 on 2026-06-10 12:13

from django.db import migrations, models


def deduplicate_emails(apps, schema_editor):
    Model = apps.get_model("newsletter", "NewsletterRegistration")
    seen = set()
    for obj in Model.objects.order_by("id"):
        if obj.email in seen:
            obj.delete()
    else:
        seen.add(obj.email)


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletterregistration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RunPython(deduplicate_emails, reverse_code=migrations.RunPython.noop),
    ]
