# Generated by Django 5.2.15 on 2026-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletterregistration_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
