/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as ReserveShowIdRouteImport } from './routes/reserve.$showId'
import { Route as ShowShowIdRouteImport } from './routes/show.$showId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveShowIdRoute = ReserveShowIdRouteImport.update({
  id: '/reserve/$showId',
  path: '/reserve/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowShowIdRoute = ShowShowIdRouteImport.update({
  id: '/show/$showId',
  path: '/show/$showId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/impressum': typeof ImpressumRoute
  '/rentals': typeof RentalsRoute
  '/reserve/$showId': typeof ReserveShowIdRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/impressum': typeof ImpressumRoute
  '/rentals': typeof RentalsRoute
  '/reserve/$showId': typeof ReserveShowIdRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/events': typeof EventsRoute
  '/impressum': typeof ImpressumRoute
  '/rentals': typeof RentalsRoute
  '/reserve/$showId': typeof ReserveShowIdRoute
  '/show/$showId': typeof ShowShowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/rentals'
    | '/reserve/$showId'
    | '/show/$showId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/rentals'
    | '/reserve/$showId'
    | '/show/$showId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/events'
    | '/impressum'
    | '/rentals'
    | '/reserve/$showId'
    | '/show/$showId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EventsRoute: typeof EventsRoute
  ImpressumRoute: typeof ImpressumRoute
  RentalsRoute: typeof RentalsRoute
  ReserveShowIdRoute: typeof ReserveShowIdRoute
  ShowShowIdRoute: typeof ShowShowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/$showId': {
      id: '/reserve/$showId'
      path: '/reserve/$showId'
      fullPath: '/reserve/$showId'
      preLoaderRoute: typeof ReserveShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$showId': {
      id: '/show/$showId'
      path: '/show/$showId'
      fullPath: '/show/$showId'
      preLoaderRoute: typeof ShowShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DatenschutzRoute: DatenschutzRoute,
  EventsRoute: EventsRoute,
  ImpressumRoute: ImpressumRoute,
  RentalsRoute: RentalsRoute,
  ReserveShowIdRoute: ReserveShowIdRoute,
  ShowShowIdRoute: ShowShowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
