/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as QrScannerRouteImport } from './routes/qr-scanner'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as PaymentFailureRouteImport } from './routes/payment.failure'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as ReserveShowIdRouteImport } from './routes/reserve.$showId'
import { Route as ShowShowIdRouteImport } from './routes/show.$showId'
import { Route as ReserveShowIdPaymentRouteImport } from './routes/reserve.$showId_.payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const QrScannerRoute = QrScannerRouteImport.update({
  id: '/qr-scanner',
  path: '/qr-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailureRoute = PaymentFailureRouteImport.update({
  id: '/payment/failure',
  path: '/payment/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveShowIdRoute = ReserveShowIdRouteImport.update({
  id: '/reserve/$showId',
  path: '/reserve/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowShowIdRoute = ShowShowIdRouteImport.update({
  id: '/show/$showId',
  path: '/show/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveShowIdPaymentRoute = ReserveShowIdPaymentRouteImport.update({
  id: '/reserve/$showId_/payment',
  path: '/reserve/$showId/payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/qr-scanner': typeof QrScannerRoute
  '/rentals': typeof RentalsRoute
  '/shows': typeof ShowsRoute
  '/api/$': typeof ApiSplatRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/reserve/$showId': typeof ReserveShowIdRoute
  '/show/$showId': typeof ShowShowIdRoute
  '/reserve/$showId/payment': typeof ReserveShowIdPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/qr-scanner': typeof QrScannerRoute
  '/rentals': typeof RentalsRoute
  '/shows': typeof ShowsRoute
  '/api/$': typeof ApiSplatRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/reserve/$showId': typeof ReserveShowIdRoute
  '/show/$showId': typeof ShowShowIdRoute
  '/reserve/$showId/payment': typeof ReserveShowIdPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/qr-scanner': typeof QrScannerRoute
  '/rentals': typeof RentalsRoute
  '/shows': typeof ShowsRoute
  '/api/$': typeof ApiSplatRoute
  '/payment/failure': typeof PaymentFailureRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/reserve/$showId': typeof ReserveShowIdRoute
  '/show/$showId': typeof ShowShowIdRoute
  '/reserve/$showId_/payment': typeof ReserveShowIdPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/qr-scanner'
    | '/rentals'
    | '/shows'
    | '/api/$'
    | '/payment/failure'
    | '/payment/success'
    | '/reserve/$showId'
    | '/show/$showId'
    | '/reserve/$showId/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/qr-scanner'
    | '/rentals'
    | '/shows'
    | '/api/$'
    | '/payment/failure'
    | '/payment/success'
    | '/reserve/$showId'
    | '/show/$showId'
    | '/reserve/$showId/payment'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/datenschutz'
    | '/impressum'
    | '/qr-scanner'
    | '/rentals'
    | '/shows'
    | '/api/$'
    | '/payment/failure'
    | '/payment/success'
    | '/reserve/$showId'
    | '/show/$showId'
    | '/reserve/$showId_/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  QrScannerRoute: typeof QrScannerRoute
  RentalsRoute: typeof RentalsRoute
  ShowsRoute: typeof ShowsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  PaymentFailureRoute: typeof PaymentFailureRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ReserveShowIdRoute: typeof ReserveShowIdRoute
  ShowShowIdRoute: typeof ShowShowIdRoute
  ReserveShowIdPaymentRoute: typeof ReserveShowIdPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-scanner': {
      id: '/qr-scanner'
      path: '/qr-scanner'
      fullPath: '/qr-scanner'
      preLoaderRoute: typeof QrScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failure': {
      id: '/payment/failure'
      path: '/payment/failure'
      fullPath: '/payment/failure'
      preLoaderRoute: typeof PaymentFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/$showId': {
      id: '/reserve/$showId'
      path: '/reserve/$showId'
      fullPath: '/reserve/$showId'
      preLoaderRoute: typeof ReserveShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$showId': {
      id: '/show/$showId'
      path: '/show/$showId'
      fullPath: '/show/$showId'
      preLoaderRoute: typeof ShowShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/$showId_/payment': {
      id: '/reserve/$showId_/payment'
      path: '/reserve/$showId/payment'
      fullPath: '/reserve/$showId/payment'
      preLoaderRoute: typeof ReserveShowIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  QrScannerRoute: QrScannerRoute,
  RentalsRoute: RentalsRoute,
  ShowsRoute: ShowsRoute,
  ApiSplatRoute: ApiSplatRoute,
  PaymentFailureRoute: PaymentFailureRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ReserveShowIdRoute: ReserveShowIdRoute,
  ShowShowIdRoute: ShowShowIdRoute,
  ReserveShowIdPaymentRoute: ReserveShowIdPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
