# Generated by Django 3.2.5 on 2021-07-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zm', '0002_visitor_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
