# Generated by Django 5.2.14 on 2026-05-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("deleted_visitors", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
