# Generated by Django 5.2.15 on 2026-09-10 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteStats",
        ),
    ]
