# Generated by Django 5.2.17 on 2026-09-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stats", "0002_delete_sitestats"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("path", models.CharField(max_length=255)),
                ("referer", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                            ("bot", "Bot"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_key", "entered_at"], name="stats_pagev_session_2e9870_idx"
                    )
                ],
            },
        ),
    ]
